databases:
  - name: gabskitchen
    plan: free
    databaseName: firstdjangoproject
    user: firstapp

services:
  - type: web
    plan: free
    name: firstapp
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn firstapp.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gabskitchen
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4